# Variables reelevantes para la colocación de cajeros

### Empezamos cargando las respectivas bases que contiene informacion acerca de los cajeros y su entorno

In [488]:
import pandas as pd
import numpy as np
df1 = pd.read_csv('base1.csv', sep=',',encoding='latin-1').fillna(value = 0)
df2 = pd.read_csv('base2.csv',sep=',',encoding='latin-1').fillna(value = 0)
df3 = pd.read_csv('sucursales2.csv',sep=',',encoding='latin-1').fillna(value = 0)
df4 = pd.read_csv('base3.csv',sep=',',encoding='latin-1').fillna(value = 0)

In [489]:
df1.head()

      Ref ID CAJERO  Otros bancos  Promocion
0   824.0    J16681        1066.0          1
1   824.0    J16681         830.0          1
2   787.0    J16694         805.0          1
3  1086.0    J16643         685.0          1
4   787.0    J16694         647.0          1

In [490]:
df2.head()

   Ref  km_to_atm    km_min    km_max  cajeros60  cajeros150
0  105   0.014291  0.014291  0.014291        1.0         1.0
1  143   0.056785  0.056785  0.056785        1.0         1.0
2  146   0.031691  0.031691  0.031691        1.0         1.0
3  152   0.037341  0.037341  0.115883        1.0         3.0
4  157   0.024050  0.024050  0.121298        2.0         5.0

In [491]:
df3.head()

,Ref,CorresponsalesenMpio,ATMenMpio,TPVs,TPVsenEstablecimientos,clientescdssep,cuentasadminsep,beneficiarios TDD,totalcuentasadm,saldostotales,...,vph_telef,vph_cel,tamaño_localidad,poblaboral,per_pder_imss,per_pocupada,per_pdesocup,perprog,marginacionINEGI,Ganadora
0,401.0,91.0,54.0,1081.0,883.0,2445.0,2729.0,2162.0,20180.0,9311404.16,...,12587.0,23785.0,4.0,69523.0,0.518035,0.382023,0.020767,0.107136,2.0,0.0
1,220.0,260.0,172.0,3462.0,2882.0,3933.0,4145.0,5269.0,30614.0,25015668.41,...,36660.0,59617.0,4.0,163773.0,0.580656,0.406873,0.019434,0.172111,1.0,0.0
2,205.0,60.0,60.0,1063.0,913.0,3823.0,3992.0,3112.0,24379.0,38598307.86,...,12736.0,25627.0,4.0,75837.0,0.453010,0.386421,0.019383,0.127651,2.0,0.0
3,180.0,167.0,279.0,4245.0,3328.0,3457.0,3540.0,6022.0,19721.0,30016976.50,...,92585.0,102489.0,5.0,320029.0,0.510123,0.410749,0.023947,0.305360,1.0,0.0
4,332.0,16.0,21.0,211.0,178.0,4952.0,5358.0,4230.0,18304.0,28486284.39,...,7584.0,7379.0,4.0,36323.0,0.143438,0.373625,0.019193,0.231097,3.0,1.0

In [541]:
list(df3)

['Ref',
 'CorresponsalesenMpio',
 'ATMenMpio',
 'TPVs',
 'TPVsenEstablecimientos',
 'clientescdssep',
 'cuentasadminsep',
 'beneficiarios TDD',
 'totalcuentasadm',
 'saldostotales',
 'saldostotcds',
 'saldostotprogramas',
 'DispersinCanalAbiertoTDD',
 'BeneficiariosCanalCerradoPF',
 'DispersinCanalCerradoPFPT',
 'BeneficiariosEntregaDirectaA',
 'DispersinEntregaDirectaAM',
 'TotaldeBeneficiarios',
 'TotalMontoDispersado',
 'SucursalPROSPERA',
 '0TransaccionesRemesasIntern',
 'remesas',
 'SucursalRemesadora',
 'Mts2',
 'Ventanillas',
 'Empleados',
 'ATMBansefi',
 'bancamultiple',
 'walmartid',
 'km_to_walmartid',
 'km5walmart',
 'km10walmart',
 'famsaid',
 'km_to_famsaid',
 'km5famsa',
 'km10famsa',
 'aztecaid',
 'km_to_aztecaid',
 'km5azteca',
 'km10azteca',
 'compartamosid',
 'km_to_compartamosid',
 'km5compartamos',
 'km10compartamos',
 'coppelid',
 'km_to_coppelid',
 'km5coppel',
 'km10coppel',
 'Sucursales competencia < 5km',
 'bancaid',
 'km_to_banca',
 'km5banca',
 'km10banca',
 'pobtot_Localidad',
 'p_15ymas',
 'p_60ymas',
 'pocupada',
 'pdesocup',
 'pdesocup_f',
 'pder_imss',
 'vivtot',
 'vph_aguadv',
 'vph_aguafv',
 'vph_excsa',
 'vph_drenaj',
 'vph_pc',
 'vph_telef',
 'vph_cel',
 'tamaño_localidad',
 'poblaboral',
 'per_pder_imss',
 'per_pocupada',
 'per_pdesocup',
 'perprog',
 'marginacionINEGI',
 'Ganadora']

In [492]:
df4.head()

,Ref,Tarjetas de Débito MPIO,Tarjetas de Crédito MPIO,Transacciones TPVs MPIO,Transacciones (ATM) MPIO,Remesas
0,100.0,5956776,2010394,4738293,4690668,702.0
1,101.0,1193089,463729,1043617,2396978,12.0
2,102.0,620202,258189,477898,1090612,61.0
3,103.0,1091755,360228,1947721,1555966,34.0
4,104.0,2463577,459237,3278237,2587407,16.0

### Se unen las bases de datos en base a la Referencia de la Sucursal

In [493]:
df=pd.merge(df2,df1,on="Ref")

In [494]:
df=pd.merge(df,df4,on="Ref").fillna("")

In [495]:
df.head()

,Ref,km_to_atm,km_min,km_max,cajeros60,cajeros150,ID CAJERO,Otros bancos,Promocion,Tarjetas de Débito MPIO,Tarjetas de Crédito MPIO,Transacciones TPVs MPIO,Transacciones (ATM) MPIO,Remesas
0,157,0.024050,0.024050,0.121298,2.0,5.0,J16607,159.0,0,573188,194796,1380898,1338067,26.0
1,157,0.024050,0.024050,0.121298,2.0,5.0,J16607,108.0,0,573188,194796,1380898,1338067,26.0
2,157,0.024050,0.024050,0.121298,2.0,5.0,J16607,72.0,0,573188,194796,1380898,1338067,26.0
3,200,0.035615,0.035615,0.136708,2.0,4.0,J16612,26.0,0,841960,160853,565858,1056293,83.0
4,200,0.035615,0.035615,0.136708,2.0,4.0,J16612,19.0,0,841960,160853,565858,1056293,83.0

### El indice de la base de datos total es el identificador del cajero

In [496]:
dfc=df.copy()

In [497]:
df['indice'] = df['ID CAJERO']
df.set_index('indice', inplace=True)

### El interes radica en las transacciones de otros bancos en nuestro cajero

In [498]:
df = pd.concat([df['Otros bancos' ],df.drop('Otros bancos' ,axis=1)], axis=1)

In [499]:
del df['ID CAJERO']
del df['Ref']

### Asi queda la base de datos final, considerando ya la correlación de las variables y su contribucion real al problema

In [500]:
df

,Otros bancos,km_to_atm,km_min,km_max,cajeros60,cajeros150,Promocion,Tarjetas de Débito MPIO,Tarjetas de Crédito MPIO,Transacciones TPVs MPIO,Transacciones (ATM) MPIO,Remesas
indice,,,,,,,,,,,,
J16607,159.0,0.024050,0.024050,0.121298,2.0,5.0,0,573188,194796,1380898,1338067,26.0
J16607,108.0,0.024050,0.024050,0.121298,2.0,5.0,0,573188,194796,1380898,1338067,26.0
J16607,72.0,0.024050,0.024050,0.121298,2.0,5.0,0,573188,194796,1380898,1338067,26.0
J16612,26.0,0.035615,0.035615,0.136708,2.0,4.0,0,841960,160853,565858,1056293,83.0
J16612,19.0,0.035615,0.035615,0.136708,2.0,4.0,0,841960,160853,565858,1056293,83.0
J16612,1.0,0.035615,0.035615,0.136708,2.0,4.0,0,841960,160853,565858,1056293,83.0
J16617,41.0,0.031066,0.061221,0.124697,1.0,5.0,0,836191,199806,1061668,1104881,47.0
J16617,27.0,0.031066,0.061221,0.124697,1.0,5.0,0,836191,199806,1061668,1104881,47.0
J16617,13.0,0.031066,0.061221,0.124697,1.0,5.0,0,836191,199806,1061668,1104881,47.0
J16644,11.0,0.031833,0.031833,0.128369,1.0,4.0,0,1532605,332332,1883621,1620234,158.0
J16644,10.0,0.031833,0.031833,0.128369,1.0,4.0,0,1532605,332332,1883621,1620234,158.0
J16644,6.0,0.031833,0.031833,0.128369,1.0,4.0,0,1532605,332332,1883621,1620234,158.0
J16638,16.0,0.033287,0.033287,0.033287,1.0,1.0,0,1216718,305709,3571476,2548878,92.0
J16638,12.0,0.033287,0.033287,0.033287,1.0,1.0,0,1216718,305709,3571476,2548878,92.0
J16638,1.0,0.033287,0.033287,0.033287,1.0,1.0,0,1216718,305709,3571476,2548878,92.0
J16645,4.0,0.054837,0.054837,0.122895,1.0,3.0,0,1167350,276283,2997121,2115485,52.0
J16645,2.0,0.054837,0.054837,0.122895,1.0,3.0,0,1167350,276283,2997121,2115485,52.0
J16645,1.0,0.054837,0.054837,0.122895,1.0,3.0,0,1167350,276283,2997121,2115485,52.0
J16618,104.0,0.009079,0.026134,0.143672,3.0,4.0,0,776903,228286,1038834,1323868,64.0
J16618,16.0,0.009079,0.026134,0.143672,3.0,4.0,0,776903,228286,1038834,1323868,64.0
J16618,9.0,0.009079,0.026134,0.143672,3.0,4.0,0,776903,228286,1038834,1323868,64.0
J16665,10.0,0.058851,0.058851,0.058851,1.0,1.0,0,1107996,257423,2934215,2476371,69.0
J16665,4.0,0.058851,0.058851,0.058851,1.0,1.0,0,1107996,257423,2934215,2476371,69.0
J16665,3.0,0.058851,0.058851,0.058851,1.0,1.0,0,1107996,257423,2934215,2476371,69.0
J16615,13.0,0.010307,0.010307,0.139199,4.0,8.0,0,4067051,655534,6053284,4249985,109.0
J16615,6.0,0.010307,0.010307,0.139199,4.0,8.0,0,4067051,655534,6053284,4249985,109.0
J16615,5.0,0.010307,0.010307,0.139199,4.0,8.0,0,4067051,655534,6053284,4249985,109.0
J16647,40.0,0.050560,0.050560,0.111932,1.0,3.0,0,297478,62696,172163,430748,93.0
J16647,37.0,0.050560,0.050560,0.111932,1.0,3.0,0,297478,62696,172163,430748,93.0
J16647,10.0,0.050560,0.050560,0.111932,1.0,3.0,0,297478,62696,172163,430748,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...
J16682,551.0,0.000000,0.000000,0.000000,0.0,0.0,1,3371,640,491,2443,138.0
J16682,422.0,0.000000,0.000000,0.000000,0.0,0.0,0,3371,640,491,2443,138.0
J16682,390.0,0.000000,0.000000,0.000000,0.0,0.0,0,3371,640,491,2443,138.0
J166148,18.0,0.000000,0.000000,0.000000,0.0,0.0,0,16763,1254,2520,11986,729.0
J166148,2.0,0.000000,0.000000,0.000000,0.0,0.0,0,16763,1254,2520,11986,729.0
J166148,0.0,0.000000,0.000000,0.000000,0.0,0.0,0,16763,1254,2520,11986,729.0
J166143,24.0,0.119783,0.119783,0.119783,0.0,1.0,0,2593,610,11906,80524,918.0
J166143,12.0,0.119783,0.119783,0.119783,0.0,1.0,0,2593,610,11906,80524,918.0
J166143,4.0,0.119783,0.119783,0.119783,0.0,1.0,0,2593,610,11906,80524,918.0
J16601,288.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J166103,222.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J16601,211.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J166103,206.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J16631,185.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J16631,148.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J16601,144.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J166102,119.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J166103,94.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J16631,77.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J166102,61.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J166102,25.0,0.000000,0.000000,0.000000,0.0,0.0,0,9335485,348157,8518245,1794941,34.0
J16639,235.0,0.000000,0.000000,0.000000,0.0,0.0,0,250597,46088,71084,178941,53.0
J16639,136.0,0.000000,0.000000,0.000000,0.0,0.0,0,250597,46088,71084,178941,53.0
J16639,96.0,0.000000,0.000000,0.000000,0.0,0.0,0,250597,46088,71084,178941,53.0
J166145,12.0,0.000000,0.000000,0.000000,0.0,0.0,0,2406,250,3461,13276,242.0
J166145,2.0,0.000000,0.000000,0.000000,0.0,0.0,0,2406,250,3461,13276,242.0
J166145,1.0,0.000000,0.000000,0.000000,0.0,0.0,0,2406,250,3461,13276,242.0
J16659,29.0,0.000000,0.000000,0.000000,0.0,0.0,0,209758,16558,40860,128910,36.0
J16659,27.0,0.000000,0.000000,0.000000,0.0,0.0,0,209758,16558,40860,128910,36.0
J16659,2.0,0.000000,0.000000,0.000000,0.0,0.0,0,209758,16558,40860,128910,36.0

In [501]:
df=df.fillna(0).dropna().astype(np.float32)

### Descripción estadistica de la base de datos

In [502]:
df.describe()

,Otros bancos,km_to_atm,km_min,km_max,cajeros60,cajeros150,Promocion,Tarjetas de Débito MPIO,Tarjetas de Crédito MPIO,Transacciones TPVs MPIO,Transacciones (ATM) MPIO,Remesas
count,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.00,3.330000e+02,3.330000e+02,333.000,333.000000
mean,70.966965,0.042478,0.043191,0.065998,0.441441,1.387387,0.024024,896492.00,1.516823e+05,9.707363e+05,871427.000,158.369370
std,131.250000,0.042618,0.042829,0.058490,0.791726,1.580216,0.153354,1833602.75,2.411316e+05,1.815135e+06,1050042.625,256.630432
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,4.400000e+01,0.000000e+00,0.000,0.000000
25%,8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,64810.00,1.133800e+04,1.396500e+04,66819.000,34.000000
50%,23.000000,0.035615,0.036484,0.062911,0.000000,1.000000,0.000000,284234.00,6.269600e+04,1.721630e+05,386657.000,69.000000
75%,70.000000,0.076558,0.079086,0.124697,1.000000,2.000000,0.000000,1013281.00,2.082400e+05,1.061668e+06,1555966.000,158.000000
max,1066.000000,0.148799,0.148799,0.149978,4.000000,8.000000,1.000000,9335485.00,2.010394e+06,8.518245e+06,4690668.000,1841.000000

### Dividimos la base de datos en un conjunto de prueba y otro de entrenamiento

In [503]:


from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor

X, y = df.iloc[:,1:], df.iloc[:, 0]




X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

### Se aplica un algoritmo de Random Forest para observar la reelevancia de las variables

In [504]:
forest = RandomForestRegressor(n_estimators=3000, random_state=2)
model=forest.fit(X_train, y_train)

In [505]:
print("Exactitud en el conjunto de entrenamiento: {:.3f}".format(forest.score(X_train, y_train)))
print("Exactitud en el conjunto de prueba: {:.3f}".format(forest.score(X_test, y_test)))

#print("Feature importances:\n{}".format(forest.feature_importances_))

headers = ["name", "score"]
values = sorted(zip(X_train.columns, model.feature_importances_*100), key=lambda x: x[1] * -1)

Exactitud en el conjunto de entrenamiento: 0.882
Exactitud en el conjunto de prueba: 0.865

### Se muestra la reelevancia númerica de las variables

In [506]:
Variables=pd.DataFrame(values,columns=["nombre", "Porcentaje "])
print(Variables)

                      nombre  Porcentaje
0                  Promocion    60.041653
1                    Remesas     9.258362
2   Transacciones (ATM) MPIO     7.356810
3   Tarjetas de Crédito MPIO     6.391594
4    Tarjetas de Débito MPIO     4.987065
5    Transacciones TPVs MPIO     3.960067
6                     km_min     2.970266
7                  km_to_atm     2.119207
8                     km_max     1.480761
9                 cajeros150     0.990979
10                 cajeros60     0.443235

### Es necesario ver cuales de estas variables hacen que las transacciones suban o bajen, por lo que se utiliza ahora una regression lineal que nos permita acercarnos a un modelo

In [507]:
from sklearn.linear_model import Lasso
lin_reg=Lasso(alpha=0.1,max_iter=100000,normalize=True)
lin_reg.fit(X,y)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=100000,
   normalize=True, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [508]:
print("Exactitud en el conjunto de entrenamiento: {:.3f}".format(lin_reg.score(X_train, y_train)))
print("Exactitud en el conjunto de prueba: {:.3f}".format(lin_reg.score(X_test, y_test)))

Exactitud en el conjunto de entrenamiento: 0.642
Exactitud en el conjunto de prueba: 0.771

In [509]:
lin_reg.intercept_, lin_reg.coef_

(30.059437054160298,
 array([  0.00000000e+00,   3.24701005e+01,  -0.00000000e+00,
         -5.32777571e+00,  -1.40590086e+00,   6.37145153e+02,
          8.78351385e-06,   4.33895489e-05,   0.00000000e+00,
         -0.00000000e+00,   8.86848499e-02]))

In [510]:
lin_reg.coef_[1]

32.470100513199746

In [511]:
coefficients = pd.DataFrame({"Caracteristicas":X.columns,"Coeficientes":np.transpose(lin_reg.coef_)})

### Los coeficientes de cada variable se enlistan a continuación

In [512]:
coefficients

             Caracteristicas  Coeficientes
0                  km_to_atm      0.000000
1                     km_min     32.470101
2                     km_max     -0.000000
3                  cajeros60     -5.327776
4                 cajeros150     -1.405901
5                  Promocion    637.145153
6    Tarjetas de Débito MPIO      0.000009
7   Tarjetas de Crédito MPIO      0.000043
8    Transacciones TPVs MPIO      0.000000
9   Transacciones (ATM) MPIO     -0.000000
10                   Remesas      0.088685

### Una buena aproximación al número de transacciones realizadas en nuestros cajeros por otros bancos es

$$ Transacciones Otros Bancos= 51.1199 + 653.83(Promoción)-33.13(Km al cajero más lejano) +13.5(Km al  cajero más cercano)-7.669866(número de instituciones/ATMs a 60 metros)$$

### Donde la Promoción viene dada por 1 o 0.

In [513]:
df.head()

,Otros bancos,km_to_atm,km_min,km_max,cajeros60,cajeros150,Promocion,Tarjetas de Débito MPIO,Tarjetas de Crédito MPIO,Transacciones TPVs MPIO,Transacciones (ATM) MPIO,Remesas
indice,,,,,,,,,,,,
J16607,159.0,0.024050,0.024050,0.121298,2.0,5.0,0.0,573188.0,194796.0,1380898.0,1338067.0,26.0
J16607,108.0,0.024050,0.024050,0.121298,2.0,5.0,0.0,573188.0,194796.0,1380898.0,1338067.0,26.0
J16607,72.0,0.024050,0.024050,0.121298,2.0,5.0,0.0,573188.0,194796.0,1380898.0,1338067.0,26.0
J16612,26.0,0.035615,0.035615,0.136708,2.0,4.0,0.0,841960.0,160853.0,565858.0,1056293.0,83.0
J16612,19.0,0.035615,0.035615,0.136708,2.0,4.0,0.0,841960.0,160853.0,565858.0,1056293.0,83.0

In [514]:
dfc.head()

,Ref,km_to_atm,km_min,km_max,cajeros60,cajeros150,ID CAJERO,Otros bancos,Promocion,Tarjetas de Débito MPIO,Tarjetas de Crédito MPIO,Transacciones TPVs MPIO,Transacciones (ATM) MPIO,Remesas
0,157,0.024050,0.024050,0.121298,2.0,5.0,J16607,159.0,0,573188,194796,1380898,1338067,26.0
1,157,0.024050,0.024050,0.121298,2.0,5.0,J16607,108.0,0,573188,194796,1380898,1338067,26.0
2,157,0.024050,0.024050,0.121298,2.0,5.0,J16607,72.0,0,573188,194796,1380898,1338067,26.0
3,200,0.035615,0.035615,0.136708,2.0,4.0,J16612,26.0,0,841960,160853,565858,1056293,83.0
4,200,0.035615,0.035615,0.136708,2.0,4.0,J16612,19.0,0,841960,160853,565858,1056293,83.0

In [515]:
list(dfc)

['Ref',
 'km_to_atm',
 'km_min',
 'km_max',
 'cajeros60',
 'cajeros150',
 'ID CAJERO',
 'Otros bancos',
 'Promocion',
 'Tarjetas de Débito MPIO',
 'Tarjetas de Crédito MPIO',
 'Transacciones TPVs MPIO',
 'Transacciones (ATM) MPIO',
 'Remesas']

In [516]:
dfc.set_index('Ref', inplace=True)

In [517]:
del dfc['ID CAJERO']
del dfc['Promocion']

In [518]:
dfc = pd.concat([dfc['Otros bancos' ],dfc.drop('Otros bancos' ,axis=1)], axis=1)

In [519]:
X1, y1 = dfc.iloc[:,1:], dfc.iloc[:, 0]




X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.2, random_state=1)

In [520]:
forest1 = RandomForestRegressor(n_estimators=3000, random_state=2)
model1=forest1.fit(X_train1, y_train1)

In [521]:
print("Exactitud en el conjunto de entrenamiento: {:.3f}".format(forest1.score(X_train1, y_train1)))
print("Exactitud en el conjunto de prueba: {:.3f}".format(forest1.score(X_test1, y_test1)))

#print("Feature importances:\n{}".format(forest.feature_importances_))

headers = ["name", "score"]
values1 = sorted(zip(X_train1.columns, model1.feature_importances_*100), key=lambda x: x[1] * -1)

Exactitud en el conjunto de entrenamiento: 0.820
Exactitud en el conjunto de prueba: 0.598

In [522]:
Variables=pd.DataFrame(values1,columns=["nombre", "Porcentaje "])
Variables

                     nombre  Porcentaje
0   Transacciones TPVs MPIO    24.097861
1                   Remesas    23.517852
2  Transacciones (ATM) MPIO    16.753130
3  Tarjetas de Crédito MPIO    14.727193
4   Tarjetas de Débito MPIO     9.690144
5                    km_min     4.247520
6                 km_to_atm     2.954986
7                    km_max     2.306199
8                cajeros150     1.294662
9                 cajeros60     0.410453

In [523]:
Variables.set_index('nombre', inplace=True)

In [524]:
Variables

                          Porcentaje
nombre
Transacciones TPVs MPIO     24.097861
Remesas                     23.517852
Transacciones (ATM) MPIO    16.753130
Tarjetas de Crédito MPIO    14.727193
Tarjetas de Débito MPIO      9.690144
km_min                       4.247520
km_to_atm                    2.954986
km_max                       2.306199
cajeros150                   1.294662
cajeros60                    0.410453

In [525]:
list(Variables)

['Porcentaje ']

In [526]:
dfl =  dfc.sum(axis=0)
dfl
dfc=dfc.div(dfl, axis=1)

In [527]:
df444=dfc.multiply(Variables['Porcentaje '])

In [528]:
df444

,Otros bancos,Remesas,Tarjetas de Crédito MPIO,Tarjetas de Débito MPIO,Transacciones (ATM) MPIO,Transacciones TPVs MPIO,cajeros150,cajeros60,km_max,km_min,km_to_atm
Ref,,,,,,,,,,,
157,NaN,0.011595,0.056796,0.018605,0.077250,0.102942,0.014011,0.005584,0.012729,0.007103,0.005024
157,NaN,0.011595,0.056796,0.018605,0.077250,0.102942,0.014011,0.005584,0.012729,0.007103,0.005024
157,NaN,0.011595,0.056796,0.018605,0.077250,0.102942,0.014011,0.005584,0.012729,0.007103,0.005024
200,NaN,0.037014,0.046900,0.027329,0.060982,0.042183,0.011209,0.005584,0.014346,0.010518,0.007440
200,NaN,0.037014,0.046900,0.027329,0.060982,0.042183,0.011209,0.005584,0.014346,0.010518,0.007440
200,NaN,0.037014,0.046900,0.027329,0.060982,0.042183,0.011209,0.005584,0.014346,0.010518,0.007440
209,NaN,0.020959,0.058257,0.027142,0.063788,0.079145,0.014011,0.002792,0.013085,0.018080,0.006490
209,NaN,0.020959,0.058257,0.027142,0.063788,0.079145,0.014011,0.002792,0.013085,0.018080,0.006490
209,NaN,0.020959,0.058257,0.027142,0.063788,0.079145,0.014011,0.002792,0.013085,0.018080,0.006490
210,NaN,0.070459,0.096898,0.049747,0.093540,0.140419,0.011209,0.002792,0.013470,0.009401,0.006650
210,NaN,0.070459,0.096898,0.049747,0.093540,0.140419,0.011209,0.002792,0.013470,0.009401,0.006650
210,NaN,0.070459,0.096898,0.049747,0.093540,0.140419,0.011209,0.002792,0.013470,0.009401,0.006650
211,NaN,0.041027,0.089135,0.039494,0.147153,0.266245,0.002802,0.002792,0.003493,0.009830,0.006954
211,NaN,0.041027,0.089135,0.039494,0.147153,0.266245,0.002802,0.002792,0.003493,0.009830,0.006954
211,NaN,0.041027,0.089135,0.039494,0.147153,0.266245,0.002802,0.002792,0.003493,0.009830,0.006954
215,NaN,0.023189,0.080555,0.037891,0.122132,0.223428,0.008407,0.002792,0.012896,0.016194,0.011456
215,NaN,0.023189,0.080555,0.037891,0.122132,0.223428,0.008407,0.002792,0.012896,0.016194,0.011456
215,NaN,0.023189,0.080555,0.037891,0.122132,0.223428,0.008407,0.002792,0.012896,0.016194,0.011456
217,NaN,0.028541,0.066561,0.025218,0.076430,0.077442,0.011209,0.008377,0.015076,0.007718,0.001897
217,NaN,0.028541,0.066561,0.025218,0.076430,0.077442,0.011209,0.008377,0.015076,0.007718,0.001897
217,NaN,0.028541,0.066561,0.025218,0.076430,0.077442,0.011209,0.008377,0.015076,0.007718,0.001897
224,NaN,0.030770,0.075056,0.035965,0.142967,0.218738,0.002802,0.002792,0.006176,0.017380,0.012294
224,NaN,0.030770,0.075056,0.035965,0.142967,0.218738,0.002802,0.002792,0.006176,0.017380,0.012294
224,NaN,0.030770,0.075056,0.035965,0.142967,0.218738,0.002802,0.002792,0.006176,0.017380,0.012294
225,NaN,0.048608,0.191133,0.132014,0.245362,0.451257,0.022418,0.011169,0.014607,0.003044,0.002153
225,NaN,0.048608,0.191133,0.132014,0.245362,0.451257,0.022418,0.011169,0.014607,0.003044,0.002153
225,NaN,0.048608,0.191133,0.132014,0.245362,0.451257,0.022418,0.011169,0.014607,0.003044,0.002153
230,NaN,0.041473,0.018280,0.009656,0.024868,0.012834,0.008407,0.002792,0.011746,0.014931,0.010562
230,NaN,0.041473,0.018280,0.009656,0.024868,0.012834,0.008407,0.002792,0.011746,0.014931,0.010562
230,NaN,0.041473,0.018280,0.009656,0.024868,0.012834,0.008407,0.002792,0.011746,0.014931,0.010562
...,...,...,...,...,...,...,...,...,...,...,...
825,NaN,0.061541,0.000187,0.000109,0.000141,0.000037,0.000000,0.000000,0.000000,0.000000,0.000000
825,NaN,0.061541,0.000187,0.000109,0.000141,0.000037,0.000000,0.000000,0.000000,0.000000,0.000000
825,NaN,0.061541,0.000187,0.000109,0.000141,0.000037,0.000000,0.000000,0.000000,0.000000,0.000000
841,NaN,0.325095,0.000366,0.000544,0.000692,0.000188,0.000000,0.000000,0.000000,0.000000,0.000000
841,NaN,0.325095,0.000366,0.000544,0.000692,0.000188,0.000000,0.000000,0.000000,0.000000,0.000000
841,NaN,0.325095,0.000366,0.000544,0.000692,0.000188,0.000000,0.000000,0.000000,0.000000,0.000000
857,NaN,0.409378,0.000178,0.000084,0.004649,0.000888,0.002802,0.000000,0.012569,0.035374,0.025023
857,NaN,0.409378,0.000178,0.000084,0.004649,0.000888,0.002802,0.000000,0.012569,0.035374,0.025023
857,NaN,0.409378,0.000178,0.000084,0.004649,0.000888,0.002802,0.000000,0.012569,0.035374,0.025023
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000
909,NaN,0.023635,0.013438,0.008134,0.010331,0.005299,0.000000,0.000000,0.000000,0.000000,0.000000
909,NaN,0.023635,0.013438,0.008134,0.010331,0.005299,0.000000,0.000000,0.000000,0.000000,0.000000
909,NaN,0.023635,0.013438,0.008134,0.010331,0.005299,0.000000,0.000000,0.000000,0.000000,0.000000
923,NaN,0.107919,0.000073,0.000078,0.000766,0.000258,0.000000,0.000000,0.000000,0.000000,0.000000
923,NaN,0.107919,0.000073,0.000078,0.000766,0.000258,0.000000,0.000000,0.000000,0.000000,0.000000
923,NaN,0.107919,0.000073,0.000078,0.000766,0.000258,0.000000,0.000000,0.000000,0.000000,0.000000
989,NaN,0.016054,0.004828,0.006809,0.007442,0.003046,0.000000,0.000000,0.000000,0.000000,0.000000
989,NaN,0.016054,0.004828,0.006809,0.007442,0.003046,0.000000,0.000000,0.000000,0.000000,0.000000
989,NaN,0.016054,0.004828,0.006809,0.007442,0.003046,0.000000,0.000000,0.000000,0.000000,0.000000

In [529]:
df444['Score'] =  df444.sum(axis=1)

In [530]:
df444

,Otros bancos,Remesas,Tarjetas de Crédito MPIO,Tarjetas de Débito MPIO,Transacciones (ATM) MPIO,Transacciones TPVs MPIO,cajeros150,cajeros60,km_max,km_min,km_to_atm,Score
Ref,,,,,,,,,,,,
157,NaN,0.011595,0.056796,0.018605,0.077250,0.102942,0.014011,0.005584,0.012729,0.007103,0.005024,0.311640
157,NaN,0.011595,0.056796,0.018605,0.077250,0.102942,0.014011,0.005584,0.012729,0.007103,0.005024,0.311640
157,NaN,0.011595,0.056796,0.018605,0.077250,0.102942,0.014011,0.005584,0.012729,0.007103,0.005024,0.311640
200,NaN,0.037014,0.046900,0.027329,0.060982,0.042183,0.011209,0.005584,0.014346,0.010518,0.007440,0.263506
200,NaN,0.037014,0.046900,0.027329,0.060982,0.042183,0.011209,0.005584,0.014346,0.010518,0.007440,0.263506
200,NaN,0.037014,0.046900,0.027329,0.060982,0.042183,0.011209,0.005584,0.014346,0.010518,0.007440,0.263506
209,NaN,0.020959,0.058257,0.027142,0.063788,0.079145,0.014011,0.002792,0.013085,0.018080,0.006490,0.303749
209,NaN,0.020959,0.058257,0.027142,0.063788,0.079145,0.014011,0.002792,0.013085,0.018080,0.006490,0.303749
209,NaN,0.020959,0.058257,0.027142,0.063788,0.079145,0.014011,0.002792,0.013085,0.018080,0.006490,0.303749
210,NaN,0.070459,0.096898,0.049747,0.093540,0.140419,0.011209,0.002792,0.013470,0.009401,0.006650,0.494587
210,NaN,0.070459,0.096898,0.049747,0.093540,0.140419,0.011209,0.002792,0.013470,0.009401,0.006650,0.494587
210,NaN,0.070459,0.096898,0.049747,0.093540,0.140419,0.011209,0.002792,0.013470,0.009401,0.006650,0.494587
211,NaN,0.041027,0.089135,0.039494,0.147153,0.266245,0.002802,0.002792,0.003493,0.009830,0.006954,0.608925
211,NaN,0.041027,0.089135,0.039494,0.147153,0.266245,0.002802,0.002792,0.003493,0.009830,0.006954,0.608925
211,NaN,0.041027,0.089135,0.039494,0.147153,0.266245,0.002802,0.002792,0.003493,0.009830,0.006954,0.608925
215,NaN,0.023189,0.080555,0.037891,0.122132,0.223428,0.008407,0.002792,0.012896,0.016194,0.011456,0.538941
215,NaN,0.023189,0.080555,0.037891,0.122132,0.223428,0.008407,0.002792,0.012896,0.016194,0.011456,0.538941
215,NaN,0.023189,0.080555,0.037891,0.122132,0.223428,0.008407,0.002792,0.012896,0.016194,0.011456,0.538941
217,NaN,0.028541,0.066561,0.025218,0.076430,0.077442,0.011209,0.008377,0.015076,0.007718,0.001897,0.318469
217,NaN,0.028541,0.066561,0.025218,0.076430,0.077442,0.011209,0.008377,0.015076,0.007718,0.001897,0.318469
217,NaN,0.028541,0.066561,0.025218,0.076430,0.077442,0.011209,0.008377,0.015076,0.007718,0.001897,0.318469
224,NaN,0.030770,0.075056,0.035965,0.142967,0.218738,0.002802,0.002792,0.006176,0.017380,0.012294,0.544941
224,NaN,0.030770,0.075056,0.035965,0.142967,0.218738,0.002802,0.002792,0.006176,0.017380,0.012294,0.544941
224,NaN,0.030770,0.075056,0.035965,0.142967,0.218738,0.002802,0.002792,0.006176,0.017380,0.012294,0.544941
225,NaN,0.048608,0.191133,0.132014,0.245362,0.451257,0.022418,0.011169,0.014607,0.003044,0.002153,1.121765
225,NaN,0.048608,0.191133,0.132014,0.245362,0.451257,0.022418,0.011169,0.014607,0.003044,0.002153,1.121765
225,NaN,0.048608,0.191133,0.132014,0.245362,0.451257,0.022418,0.011169,0.014607,0.003044,0.002153,1.121765
230,NaN,0.041473,0.018280,0.009656,0.024868,0.012834,0.008407,0.002792,0.011746,0.014931,0.010562,0.155550
230,NaN,0.041473,0.018280,0.009656,0.024868,0.012834,0.008407,0.002792,0.011746,0.014931,0.010562,0.155550
230,NaN,0.041473,0.018280,0.009656,0.024868,0.012834,0.008407,0.002792,0.011746,0.014931,0.010562,0.155550
...,...,...,...,...,...,...,...,...,...,...,...,...
825,NaN,0.061541,0.000187,0.000109,0.000141,0.000037,0.000000,0.000000,0.000000,0.000000,0.000000,0.062014
825,NaN,0.061541,0.000187,0.000109,0.000141,0.000037,0.000000,0.000000,0.000000,0.000000,0.000000,0.062014
825,NaN,0.061541,0.000187,0.000109,0.000141,0.000037,0.000000,0.000000,0.000000,0.000000,0.000000,0.062014
841,NaN,0.325095,0.000366,0.000544,0.000692,0.000188,0.000000,0.000000,0.000000,0.000000,0.000000,0.326884
841,NaN,0.325095,0.000366,0.000544,0.000692,0.000188,0.000000,0.000000,0.000000,0.000000,0.000000,0.326884
841,NaN,0.325095,0.000366,0.000544,0.000692,0.000188,0.000000,0.000000,0.000000,0.000000,0.000000,0.326884
857,NaN,0.409378,0.000178,0.000084,0.004649,0.000888,0.002802,0.000000,0.012569,0.035374,0.025023,0.490946
857,NaN,0.409378,0.000178,0.000084,0.004649,0.000888,0.002802,0.000000,0.012569,0.035374,0.025023,0.490946
857,NaN,0.409378,0.000178,0.000084,0.004649,0.000888,0.002802,0.000000,0.012569,0.035374,0.025023,0.490946
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
909,NaN,0.023635,0.013438,0.008134,0.010331,0.005299,0.000000,0.000000,0.000000,0.000000,0.000000,0.060837
909,NaN,0.023635,0.013438,0.008134,0.010331,0.005299,0.000000,0.000000,0.000000,0.000000,0.000000,0.060837
909,NaN,0.023635,0.013438,0.008134,0.010331,0.005299,0.000000,0.000000,0.000000,0.000000,0.000000,0.060837
923,NaN,0.107919,0.000073,0.000078,0.000766,0.000258,0.000000,0.000000,0.000000,0.000000,0.000000,0.109094
923,NaN,0.107919,0.000073,0.000078,0.000766,0.000258,0.000000,0.000000,0.000000,0.000000,0.000000,0.109094
923,NaN,0.107919,0.000073,0.000078,0.000766,0.000258,0.000000,0.000000,0.000000,0.000000,0.000000,0.109094
989,NaN,0.016054,0.004828,0.006809,0.007442,0.003046,0.000000,0.000000,0.000000,0.000000,0.000000,0.038179
989,NaN,0.016054,0.004828,0.006809,0.007442,0.003046,0.000000,0.000000,0.000000,0.000000,0.000000,0.038179
989,NaN,0.016054,0.004828,0.006809,0.007442,0.003046,0.000000,0.000000,0.000000,0.000000,0.000000,0.038179

In [531]:
df444=df444.sort_values('Score',ascending=False)

In [532]:
df4444 = df444[~df444.index.duplicated(keep='last')]

In [533]:
df4444

,Otros bancos,Remesas,Tarjetas de Crédito MPIO,Tarjetas de Débito MPIO,Transacciones (ATM) MPIO,Transacciones TPVs MPIO,cajeros150,cajeros60,km_max,km_min,km_to_atm,Score
Ref,,,,,,,,,,,,
100,NaN,0.313054,0.586168,0.193353,0.270804,0.353228,0.005605,0.000000,0.015517,0.042374,0.029974,1.810076
908,NaN,0.015162,0.101512,0.303024,0.103626,0.635014,0.000000,0.000000,0.000000,0.000000,0.000000,1.158338
225,NaN,0.048608,0.191133,0.132014,0.245362,0.451257,0.022418,0.011169,0.014607,0.003044,0.002153,1.121765
260,NaN,0.047716,0.222949,0.096231,0.248642,0.186803,0.002802,0.002792,0.005204,0.014646,0.010361,0.838148
598,NaN,0.820987,0.000237,0.000101,0.000006,0.000041,0.000000,0.000000,0.000000,0.000000,0.000000,0.821371
234,NaN,0.031216,0.157117,0.070948,0.198898,0.191474,0.011209,0.005584,0.008679,0.012304,0.008704,0.696132
347,NaN,0.010703,0.157117,0.070948,0.198898,0.191474,0.002802,0.002792,0.003299,0.009285,0.006568,0.653885
235,NaN,0.034784,0.105138,0.044866,0.159998,0.202425,0.002802,0.000000,0.010529,0.029631,0.020960,0.611132
211,NaN,0.041027,0.089135,0.039494,0.147153,0.266245,0.002802,0.002792,0.003493,0.009830,0.006954,0.608925
226,NaN,0.106135,0.082450,0.029312,0.087325,0.300115,0.000000,0.000000,0.000000,0.000000,0.000000,0.605337
224,NaN,0.030770,0.075056,0.035965,0.142967,0.218738,0.002802,0.002792,0.006176,0.017380,0.012294,0.544941
215,NaN,0.023189,0.080555,0.037891,0.122132,0.223428,0.008407,0.002792,0.012896,0.016194,0.011456,0.538941
213,NaN,0.038797,0.107730,0.038294,0.130867,0.122506,0.008407,0.000000,0.014314,0.026250,0.018569,0.505735
210,NaN,0.070459,0.096898,0.049747,0.093540,0.140419,0.011209,0.002792,0.013470,0.009401,0.006650,0.494587
857,NaN,0.409378,0.000178,0.000084,0.004649,0.000888,0.002802,0.000000,0.012569,0.035374,0.025023,0.490946
787,NaN,0.462000,0.000779,0.000697,0.001714,0.000666,0.000000,0.000000,0.000000,0.000000,0.000000,0.465856
246,NaN,0.021851,0.102502,0.065540,0.135257,0.128556,0.000000,0.000000,0.000000,0.000000,0.000000,0.453705
238,NaN,0.016500,0.060716,0.032890,0.110164,0.143198,0.008407,0.000000,0.015424,0.035942,0.025425,0.448667
765,NaN,0.376378,0.001436,0.001107,0.001694,0.000306,0.008407,0.000000,0.010929,0.024504,0.017333,0.442094
1086,NaN,0.001338,0.135209,0.038727,0.138384,0.077799,0.002802,0.002792,0.006075,0.017096,0.012094,0.432316
182,NaN,0.012932,0.105031,0.035438,0.089830,0.145198,0.002802,0.000000,0.006737,0.018960,0.013412,0.430340
422,NaN,0.019622,0.056428,0.036777,0.105917,0.176285,0.005605,0.002792,0.010638,0.008989,0.006359,0.429411
522,NaN,0.382622,0.000120,0.000256,0.000295,0.000077,0.000000,0.000000,0.000000,0.000000,0.000000,0.383369
141,NaN,0.012041,0.081051,0.054011,0.079655,0.089183,0.005605,0.000000,0.015738,0.026000,0.018392,0.381676
111,NaN,0.025419,0.116574,0.029558,0.113815,0.085776,0.000000,0.000000,0.000000,0.000000,0.000000,0.371142
329,NaN,0.048608,0.073150,0.035037,0.102069,0.108041,0.000000,0.000000,0.000000,0.000000,0.000000,0.366905
251,NaN,0.008473,0.056552,0.031014,0.094619,0.102045,0.005605,0.000000,0.013769,0.026553,0.018783,0.357413
841,NaN,0.325095,0.000366,0.000544,0.000692,0.000188,0.000000,0.000000,0.000000,0.000000,0.000000,0.326884
137,NaN,0.017838,0.098683,0.034251,0.098455,0.069807,0.000000,0.000000,0.000000,0.000000,0.000000,0.319034
217,NaN,0.028541,0.066561,0.025218,0.076430,0.077442,0.011209,0.008377,0.015076,0.007718,0.001897,0.318469
...,...,...,...,...,...,...,...,...,...,...,...,...
644,NaN,0.043703,0.002947,0.002104,0.003464,0.000930,0.002802,0.000000,0.011513,0.032400,0.022919,0.122783
208,NaN,0.053514,0.019635,0.010023,0.022953,0.014963,0.000000,0.000000,0.000000,0.000000,0.000000,0.121087
336,NaN,0.048162,0.009646,0.003947,0.005515,0.002847,0.008407,0.002792,0.014000,0.010774,0.007622,0.113711
275,NaN,0.027649,0.017260,0.007630,0.021177,0.012862,0.008407,0.005584,0.008805,0.001788,0.001265,0.112426
313,NaN,0.073581,0.010708,0.007805,0.013314,0.005275,0.000000,0.000000,0.000000,0.000000,0.000000,0.110683
923,NaN,0.107919,0.000073,0.000078,0.000766,0.000258,0.000000,0.000000,0.000000,0.000000,0.000000,0.109094
263,NaN,0.028541,0.019900,0.013167,0.024882,0.020992,0.000000,0.000000,0.000000,0.000000,0.000000,0.107482
314,NaN,0.027203,0.001723,0.001589,0.003398,0.000401,0.008407,0.000000,0.014884,0.027843,0.019695,0.105143
305,NaN,0.026311,0.011150,0.005309,0.015172,0.007346,0.008407,0.005584,0.014833,0.006280,0.004442,0.104835
429,NaN,0.084730,0.007170,0.003212,0.005380,0.001701,0.000000,0.000000,0.000000,0.000000,0.000000,0.102192
315,NaN,0.045486,0.001589,0.000475,0.002686,0.000841,0.002802,0.000000,0.008034,0.022609,0.015993,0.100516
359,NaN,0.025419,0.007295,0.004624,0.007339,0.002611,0.016814,0.002792,0.015529,0.009439,0.006677,0.098540
696,NaN,0.043257,0.000536,0.000108,0.000671,0.000156,0.005605,0.000000,0.009443,0.020513,0.014511,0.094800
281,NaN,0.009811,0.009039,0.007306,0.015053,0.005390,0.008407,0.005584,0.010295,0.013897,0.009830,0.094613
645,NaN,0.056189,0.000058,0.000614,0.000106,0.000003,0.002802,0.002792,0.005052,0.014219,0.010058,0.091894
799,NaN,0.003568,0.003306,0.002015,0.003948,0.001696,0.008407,0.000000,0.014960,0.030720,0.021731,0.090350
774,NaN,0.076703,0.003769,0.003266,0.003725,0.001254,0.000000,0.000000,0.000000,0.000000,0.000000,0.088716
661,NaN,0.073581,0.000071,0.000856,0.000437,0.000005,0.000000,0.000000,0.000000,0.000000,0.000000,0.074949
121,NaN,0.010257,0.027882,0.005068,0.019565,0.011868,0.000000,0.000000,0.000000,0.000000,0.000000,0.074639
348,NaN,0.000000,0.005468,0.003642,0.005584,0.001041,0.008407,0.002792,0.015705,0.017198,0.012166,0.072003
169,NaN,0.010257,0.015610,0.009226,0.020185,0.010485,0.000000,0.000000,0.000000,0.000000,0.000000,0.065762
825,NaN,0.061541,0.000187,0.000109,0.000141,0.000037,0.000000,0.000000,0.000000,0.000000,0.000000,0.062014
909,NaN,0.023635,0.013438,0.008134,0.010331,0.005299,0.000000,0.000000,0.000000,0.000000,0.000000,0.060837
320,NaN,0.020959,0.009975,0.003754,0.011344,0.005001,0.000000,0.000000,0.000000,0.000000,0.000000,0.051033
441,NaN,0.005797,0.009689,0.005559,0.016519,0.009131,0.000000,0.000000,0.000000,0.000000,0.000000,0.046695
786,NaN,0.022297,0.004916,0.002283,0.005536,0.005840,0.000000,0.000000,0.000000,0.000000,0.000000,0.040872
989,NaN,0.016054,0.004828,0.006809,0.007442,0.003046,0.000000,0.000000,0.000000,0.000000,0.000000,0.038179
264,NaN,0.014716,0.005259,0.005579,0.004760,0.001339,0.000000,0.000000,0.000000,0.000000,0.000000,0.031655
781,NaN,0.014270,0.000150,0.000379,0.000449,0.000034,0.000000,0.000000,0.000000,0.000000,0.000000,0.015281
643,NaN,0.011595,0.000102,0.000146,0.000087,0.000076,0.000000,0.000000,0.000000,0.000000,0.000000,0.012006

In [537]:
dfbueno=df4444['Score']

In [539]:
dfbueno[:50]

Ref
100     1.810076
908     1.158338
225     1.121765
260     0.838148
598     0.821371
234     0.696132
347     0.653885
235     0.611132
211     0.608925
226     0.605337
224     0.544941
215     0.538941
213     0.505735
210     0.494587
857     0.490946
787     0.465856
246     0.453705
238     0.448667
765     0.442094
1086    0.432316
182     0.430340
422     0.429411
522     0.383369
141     0.381676
111     0.371142
329     0.366905
251     0.357413
841     0.326884
137     0.319034
217     0.318469
791     0.316301
157     0.311640
209     0.303749
440     0.290920
248     0.277739
250     0.273261
242     0.271795
200     0.263506
269     0.246120
252     0.229204
662     0.223432
212     0.212565
642     0.211494
352     0.205113
221     0.199540
202     0.195356
231     0.194881
647     0.187620
638     0.183877
796     0.183547
Name: Score, dtype: float64

In [540]:
dfbueno.to_csv('Sucursalesaponercajero.csv')